### ISSUE TITLE
What the villager doing?

### ISSUE THREAD

**Issue by Acat1234** [littlej541/hands-off#1]
If you mark a bed that a villager is sleeping in then this happens
![2023-04-19_13 41 05](https://user-images.githubusercontent.com/126712560/233195917-7657b1e3-3ee5-497b-bbcd-216403b7206d.png)
They keep the sleeping pose and walk at the same time can that get fixed?

**Comment by littlej541** [comment]
It seems to be related to marking a bed when a villager is already sleeping in it after loading into a world. Can you confirm this on your end? Breaking the bed resets their pose as a temporary fix. Currently investigating the cause.

**Comment by littlej541** [comment]
I've got a fix coming out for both 1.18.2 and 1.19.2 that should solve it, but you will still have to break the bed the villager was in to correct their pose. It had to do with the several issues combining:
1. The villager AI running its path to bed at night behavior even when already in bed.
2. This mod clearing the bed location if the bed is marked when the AI tries to path to the bed.
3. The villager AI not running its sleep behavior when the game is reloaded if it was sleeping the last time the game was shutdown. This behavior is typically what kicks the villager out of bed when you mark it.

Thanks for the report. If you find any other issues or it is still occurring after you break and replace the offending bed, please be sure to let me know.
